"""dernier acces

Revision ID: 0cb6c0e784ec
Revises: bf822479be6b
Create Date: 2024-09-10 08:19:25.743651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb6c0e784ec'
down_revision = 'bf822479be6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dernier_acces', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('dernier_acces')

    # ### end Alembic commands ###
