"""table utilisateurs

Revision ID: 5337c8dae07c
Revises: 
Create Date: 2024-09-03 08:17:23.111423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5337c8dae07c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('courriel', sa.String(length=120), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateur_courriel'), ['courriel'], unique=True)
        batch_op.create_index(batch_op.f('ix_utilisateur_nom'), ['nom'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateur_nom'))
        batch_op.drop_index(batch_op.f('ix_utilisateur_courriel'))

    op.drop_table('utilisateur')
    # ### end Alembic commands ###
