"""ajout avatar

Revision ID: bf822479be6b
Revises: 0ec4ac7f8b6f
Create Date: 2024-09-03 09:36:41.478448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf822479be6b'
down_revision = '0ec4ac7f8b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(length=131072), nullable=True))
        batch_op.add_column(sa.Column('a_propos_de_moi', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('a_propos_de_moi')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
